/**
 * Generated Code Data
 *
 * Contains the mock generated React code that demonstrates the usage of
 * Visa Design System components. This code is displayed in the CodeWindow
 * component and represents what would be generated by the AI system.
 *
 * @author Josh Charpentier
 * @created 2025
 */

export const generatedCode = `import { useState } from "react"
import PromptInput from "./components/PromptInput"
import { Button, Input, Label, Textarea, Combobox } from "@visa/nova-react"

export default function LoginForm() {
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [rememberMe, setRememberMe] = useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    // Handle login logic
    console.log("Login attempt:", { email, password, rememberMe })
  }

  return (
    <div
      style={{
        maxWidth: "400px",
        margin: "0 auto",
        padding: "var(--size-responsive-20)",
        backgroundColor: "var(--palette-default-surface-1)",
        borderRadius: "var(--size-rounded-medium)",
        boxShadow: "var(--elevation-large)",
      }}
    >
      <h2
        className="v-typography-headline-2"
        style={{
          textAlign: "center",
          marginBottom: "var(--size-responsive-20)",
        }}
      >
        Login
      </h2>
      
      <form onSubmit={handleSubmit}>
        <div style={{ marginBottom: "var(--size-responsive-16)" }}>
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </div>
        
        <div style={{ marginBottom: "var(--size-responsive-16)" }}>
          <Label htmlFor="password">Password</Label>
          <Input
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>
        
        <div style={{ marginBottom: "var(--size-responsive-20)" }}>
          <input
            id="remember"
            type="checkbox"
            checked={rememberMe}
            onChange={(e) => setRememberMe(e.target.checked)}
          />
          <Label htmlFor="remember" style={{ marginLeft: "8px" }}>
            Remember me
          </Label>
        </div>
        
        <Button
          type="submit"
          style={{
            width: "100%",
            padding: "var(--size-responsive-12)",
          }}
        >
          Sign In
        </Button>
      </form>
    </div>
  )
}
`
